name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.403
      - name: Build
        working-directory: ./source
        run: dotnet build -c Release
        
  test:
    name: Tests on ${{ matrix.os }}
    needs: [ build ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.811
      - name: Setup dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.403
      - name: Test
        working-directory: ./source
        run: dotnet test --logger:trx --logger:GitHubActions
        
  benchmark:
    name: Run Benchmark.Net
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.403
      - name: Run benchmark
        working-directory: ./source/Handlebars.Extension.Benchmark
        run: dotnet run -c Release --exporters json --filter '*' -m --join
      - name: Get benchmark file name
        working-directory: ./source/Handlebars.Extension.Benchmark/BenchmarkDotNet.Artifacts/results
        id: benchmarkfilename
        run: |
          filePath=$(find . -type f -name 'BenchmarkRun-joined-*-report-full-compressed.json' | rev | cut -d '/' -f1 | rev)
          echo $filePath
          echo "::set-output name=file::$filePath"
      - name: Store benchmark result
        uses: Happypig375/github-action-benchmark@v1.8.2
        with:
          name: Benchmark.Net.Extension Benchmark
          tool: 'benchmarkdotnet'
          output-file-path: source/Handlebars.Extension.Benchmark/BenchmarkDotNet.Artifacts/results/${{ steps.benchmarkfilename.outputs.file }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false # disabled for PRs
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: false
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Benchmark
          path: source/Handlebars.Extension.Benchmark/BenchmarkDotNet.Artifacts/results/